package service.RU;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-29T17:10:36.518+03:30
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "urn:customs.ru:ForeignApi:1.0", name = "ForeignApi")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ForeignApi {

    @WebMethod(operationName = "GetMessage", action = "urn:GetMessage")
    @WebResult(name = "GetMessageResponse", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0", partName = "parameters")
    public GetMessageResponseType getMessage(

        @WebParam(partName = "parameters", name = "GetMessageRequest", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0")
        GetMessageRequestType parameters
    ) throws UnknownException, MessageNotFoundException;

    @WebMethod(operationName = "ConfirmMessage", action = "urn:ConfirmationMessage")
    @WebResult(name = "ConfirmationMessageResponse", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0", partName = "parameters")
    public ConfirmationMessageResponseType confirmMessage(

        @WebParam(partName = "parameters", name = "ConfirmationMessageRequest", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0")
        ConfirmationMessageRequestType parameters
    ) throws UnknownException, MessageNotFoundException;

    @WebMethod(operationName = "GetNewMessageList", action = "urn:GetNewMessageList")
    @WebResult(name = "GetNewMessageListResponse", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0", partName = "parameters")
    public GetNewMessageListResponseType getNewMessageList(

        @WebParam(partName = "parameters", name = "GetNewMessageListRequest", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0")
        GetNewMessageListRequestType parameters
    ) throws UnknownException;

    @WebMethod(operationName = "SendMessage", action = "urn:SendMessage")
    @WebResult(name = "SendMessageResponse", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0", partName = "parameters")
    public SendMessageResponseType sendMessage(

        @WebParam(partName = "parameters", name = "SendMessageRequest", targetNamespace = "urn:customs.ru:ForeignApi:Formats:1.0")
        SendMessageRequestType parameters
    ) throws InvalidMessageException, MessageAlreadyExistException, UnknownException;
}
