
package service.RU;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-29T17:10:36.482+03:30
 * Generated source version: 3.4.0
 */

@WebFault(name = "InvalidMessage", targetNamespace = "urn:customs.ru:ForeignApi:FaultTypes:1.0")
public class InvalidMessageException extends Exception {

    private service.RU.InvalidMessageFaultType invalidMessage;

    public InvalidMessageException() {
        super();
    }

    public InvalidMessageException(String message) {
        super(message);
    }

    public InvalidMessageException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidMessageException(String message, service.RU.InvalidMessageFaultType invalidMessage) {
        super(message);
        this.invalidMessage = invalidMessage;
    }

    public InvalidMessageException(String message, service.RU.InvalidMessageFaultType invalidMessage, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidMessage = invalidMessage;
    }

    public service.RU.InvalidMessageFaultType getFaultInfo() {
        return this.invalidMessage;
    }
}
