
package service.RU;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-29T17:10:36.501+03:30
 * Generated source version: 3.4.0
 */

@WebFault(name = "MessageAlreadyExist", targetNamespace = "urn:customs.ru:ForeignApi:FaultTypes:1.0")
public class MessageAlreadyExistException extends Exception {

    private service.RU.MessageAlreadyExistFaultType messageAlreadyExist;

    public MessageAlreadyExistException() {
        super();
    }

    public MessageAlreadyExistException(String message) {
        super(message);
    }

    public MessageAlreadyExistException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MessageAlreadyExistException(String message, service.RU.MessageAlreadyExistFaultType messageAlreadyExist) {
        super(message);
        this.messageAlreadyExist = messageAlreadyExist;
    }

    public MessageAlreadyExistException(String message, service.RU.MessageAlreadyExistFaultType messageAlreadyExist, java.lang.Throwable cause) {
        super(message, cause);
        this.messageAlreadyExist = messageAlreadyExist;
    }

    public service.RU.MessageAlreadyExistFaultType getFaultInfo() {
        return this.messageAlreadyExist;
    }
}
